---

- name: "1.1.20 CHECK: Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
  register: sticky_bit_check

- debug:
    msg: "SUCCESS: filesystem control 1.1.20"
  when: sticky_bit_check.stdout is defined and sticky_bit_check.stdout == ""

- block:
    - name: "1.1.20 ENFORCE: Ensure sticky bit is set on all world-writable directories"
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002 2>/dev/null | xargs chmod a+t
      register: sticky_bit_enforce

    - name: "1.1.20 CHECK: Ensure sticky bit is set on all world-writable directories"
      shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d ( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
      register: sticky_bit_check2
      when: sticky_bit_enforce.rc is defined and sticky_bit_enforce.rc == "0"

    - fail:
        msg: "ERROR: Failed to set sticky bit on world-writable directories, please manually check"
      when: sticky_bit_enforce.rc is defined and sticky_bit_enforce.rc != "0"

    - debug:
        msg: "SUCCESS: filesystem control 1.1.20"
      when: sticky_bit_check2.stdout is defined and sticky_bit_check2.stdout == ""

  when: sticky_bit_check.stdout is defined and sticky_bit_check.stdout != ""

