---

- name: "1.3.1 CHECK: Ensure AIDE is installed"
  shell: dpkg -s aide
  register: aide_check

- debug:
    msg: "SUCCESS: filesystem integrity control 1.3.1"
  when: aide_check.rc is defined and aide_check.rc == "0"

- block:
    - name: "1.3.1 ENFORCE: Ensure AIDE {{ item }} is installed"
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - aide
        - aide-common

    - name: "1.3.1 CHECK: Ensure AIDE is installed"
      shell: dpkg -s aide
      register: aide_check2

    - fail:
        msg: "ERROR: Failed to install AIDE, please manually check"
      when: aide_check2.rc is defined and aide_check2.rc != "0"

    - debug:
        msg: "SUCCESS: filesystem integrity control 1.3.1"
      when: aide_check2.rc is defined and aide_check2.rc == "0"

  when: aide_check.rc is defined and aide_check.rc != "0"

- name: "1.3.2 Ensure filesystem integrity is regularly checked"
  cron:
    name: "Filesystem Integrity Check"
    user: root
    minute: "{{ 59 | random }}"
    hour: "{{ 23 | random }}"
    job: "/usr/bin/aide.wrapper --config /etc/aide/aide.conf --check"

