---

- include_tasks: 1-1-1-disable-unused-fs.yml
  with_items:
    - { name: cramfs, control: "1.1.1.1" }
    - { name: freevxfs, control: "1.1.1.2" }
    - { name: jffs2, control: "1.1.1.3" }
    - { name: hfs, control: "1.1.1.4" }
    - { name: hfsplus, control: "1.1.1.5" }
    - { name: udf, control: "1.1.1.6" }

- include_tasks: 1-1-x-filesystem-partitions.yml
  with_items:
    - name: "/tmp"
      control: "1.1.2 > 1.1.4"
      options:
        - nodev
        - nosuid
    - name: "/var"
      control: "1.1.5"
    - name: "/var/tmp"
      control: "1.1.6 > 1.1.9"
      options:
        - nodev
        - nosuid
        - noexec
    - name: "/var/log"
      control: "1.1.10"
    - name: "/var/log/audit"
      control: "1.1.11"
    - name: "/home"
      control: "1.1.12 > 1.1.13"
      options:
        - nodev
    - name: "/dev/shm"
      control: "1.1.14 > 1.1.16"
      options:
        - nodev
        - nosuid
        - noexec
  loop_control:
    loop_var: fs_mount

- import_tasks: 1-1-20-filesystem-sticky-bit.yml

- import_tasks: 1-1-21-disable-automounting.yml

- import_tasks: 1-2-software-updates.yml

- import_tasks: 1-3-filesystem-integrity-checking.yml

- import_tasks: 1-4-secure-boot.yml

- import_tasks: 1-5-additional-process-hardening.yml

- import_tasks: 1-6-mandatory-access-control.yml

- import_tasks: 1-7-1-command-line-warn-banners.yml

- import_tasks: 1-7-2-gdm-login-banner.yml

- import_tasks: 2-1-inetd-services.yml

- import_tasks: 2-2-special-purpose-services.yml

- import_tasks: 2-3-service-clients.yml

- import_tasks: 3-1_3-2-network-params.yml

- import_tasks: 3-3-ipv6.yml

- import_tasks: 3-4-tcp-wrappers.yml

- include_tasks: 3-5-uncommon-net-protocols.yml
  with_items:
    - { name: dccp, control: "3.5.1 Ensure DCCP is disabled" }
    - { name: sctp, control: "3.5.2 Ensure SCTP is disabled" }
    - { name: rds, control: "3.5.3 Ensure RDS is disabled" }
    - { name: tipc, control: "3.5.4 Ensure TIPC is disabled" }

- import_tasks: 3-6-firewall-config.yml

- import_tasks: accounts.yml

- import_tasks: apparmor.yml

- import_tasks: auditd.yml

- import_tasks: filepermissions.yml

- import_tasks: fsmounts.yml

- import_tasks: kernel.yml

- import_tasks: sar.yml

- import_tasks: services.yml

- import_tasks: setuid.yml

- import_tasks: sshd.yml

- import_tasks: sudo.yml

