---

- name: Install Agent Config
  template: 
    src: ossec.conf.agent.j2 
    dest: /var/ossec/etc/ossec.conf 
    owner: ossec 
    group: root 
    mode: 0640
  ignore_errors: yes

- name: Set Permissions
  file: 
    path: /var/ossec 
    recurse: yes 
    mode: 0750 
    state: directory 
    owner: ossec 
    group: root

- name: Generate Agent Key
  shell: /var/ossec/bin/agent-auth -m {{ ossec.master }} -p 1515 -A {{ ansible_default_ipv4.address }} 
  args:
    creates: /var/ossec/etc/client.keys
  ignore_errors: yes

- name: Restart OSSEC Agent
  shell: /var/ossec/bin/ossec-control restart
  ignore_errors: yes
