---

- name: Install MySQL
  package: 
    name: {{ item }} 
    state: present
  with_items: 
    - mysql-server
    - libmysqlclient-dev
    - mysql-client

- name: Install Apache2
  package: 
    name: httpd 
    state: present
  when: ansible_distribution_file_variety == "RedHat"

- name: Install Apache2
  package:
    name: apache2
    state: present
  when: ansible_distribution_file_variety == "Debian"

- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - php 
    - libapache2-mod-php 
    - php-mysql 
    - php-curl
    - php-gd
    - php-intl 
    - php-pear 
    - php-imagick 
    - php-imap 
    - php-mcrypt 
    - php-memcache 
    - php-ming 
    - php-ps 
    - php-pspell 
    - php-recode 
    - php-snmp 
    - php-sqlite 
    - php-tidy 
    - php-xmlrpc 
    - php-xsl

- name: Enable Services
  service: name={{ item }}
  with_items:
    - apache2

    - mysqld
